#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hangman.Resource", IsApplication=true)]

namespace Hangman
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int hangman_0 = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int hangman_1 = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int hangman_2 = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int hangman_3 = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int hangman_4 = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int hangman_5 = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int Icon = 2130771974;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int AnswerView = 2130837504;
			
			// aapt resource value: 0x7F020003
			public const int button_a = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int button_b = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int button_c = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int button_d = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int button_e = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int button_f = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int button_g = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int button_h = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int button_i = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int button_j = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int button_k = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int button_l = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int button_m = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int button_n = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int button_o = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int button_p = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int button_q = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int button_r = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int button_s = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int button_t = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int button_u = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int button_v = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int button_w = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int button_x = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int button_y = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int button_z = 2130837532;
			
			// aapt resource value: 0x7F020001
			public const int CloseButton = 2130837505;
			
			// aapt resource value: 0x7F02001D
			public const int imageView1 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int linearLayout1 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int linearLayout2 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int linearLayout3 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int linearLayout4 = 2130837537;
			
			// aapt resource value: 0x7F020002
			public const int ListScoreBoard = 2130837506;
			
			// aapt resource value: 0x7F020022
			public const int textView1 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int textView2 = 2130837539;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Alert = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ScoreItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
